# Generated by Django 5.0.6 on 2024-05-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MersanaCreativity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('image', models.ImageField(upload_to='uploads/mersana_creativity', verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MersanaFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='')),
                ('image', models.ImageField(upload_to='uploads/mersana_friends', verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MersanaMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('music', models.FileField(upload_to='uploads/mersana_music', verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MersanaPaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='')),
                ('image', models.ImageField(upload_to='uploads/mersana_paints', verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MersanaPianos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('image', models.FileField(upload_to='uploads/mersana_piano', verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=False, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MersanaPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('image', models.ImageField(upload_to='uploads/mersana_pictures', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date', models.DateField(verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
        ),
        migrations.CreateModel(
            name='MersanaSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, verbose_name='')),
                ('school_address', models.CharField(max_length=200, verbose_name='')),
                ('teacher_name', models.CharField(max_length=200, verbose_name='')),
                ('image', models.FileField(upload_to='uploads/mersana_school', verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('period', models.CharField(max_length=200, verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MersanaSports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('image', models.FileField(upload_to='uploads/mersana_sports', verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MersanaTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_title', models.CharField(max_length=200, verbose_name='')),
                ('trip_date', models.DateField(verbose_name='')),
                ('city', models.CharField(max_length=200, verbose_name='')),
                ('image', models.FileField(upload_to='uploads/mersana_trip', verbose_name='')),
                ('trip_description', models.TextField(verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='MersanaVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('video', models.FileField(upload_to='uploads/mersana_videos', verbose_name='')),
                ('video_time', models.CharField(max_length=200, verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
    ]
