# Generated by Django 5.0.6 on 2024-05-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('image', models.FileField(upload_to='uploads/slider', verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/ نشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
    ]
