# Generated by Django 5.0.6 on 2024-05-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0004_alter_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(max_length=200, verbose_name='')),
                ('short_description', models.TextField(verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('image', models.FileField(upload_to='uploads/books', verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('slug', models.SlugField(max_length=200, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
    ]
