# Generated by Django 5.0.6 on 2024-05-24 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0005_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MersanaPianos',
            new_name='MersanaPiano',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/books', verbose_name=''),
        ),
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/books', verbose_name=''),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name=''),
            preserve_default=False,
        ),
    ]
