# Generated by Django 5.0.6 on 2024-05-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0006_rename_mersanapianos_mersanapiano_remove_book_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MersanaVideos',
        ),
    ]
