# Generated by Django 5.0.6 on 2024-06-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0010_alter_lastnews_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastnews',
            name='content',
            field=models.CharField(max_length=100, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='lastnews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='lastnews',
            name='image',
            field=models.ImageField(upload_to='uploads/lastnews', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='lastnews',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='lastnews',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='lastNewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/lastnewsGallery', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('lastnews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mersana_app.lastnews', verbose_name='آخرین خبر')),
            ],
        ),
    ]
