# Generated by Django 5.0.6 on 2024-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0012_lastnews_slug_alter_lastnewsgallery_lastnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastnews',
            name='slug',
            field=models.SlugField(default='', max_length=200, null=True, verbose_name='عنوان در url'),
        ),
    ]
