# Generated by Django 5.0.6 on 2024-06-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0014_alter_lastnews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='music_book',
            field=models.URLField(null=True, verbose_name='لینک صدای داستان'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='توضیحات اصلی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/books', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیر فعال'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/books', verbose_name='تصویر دوم'),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.TextField(verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_book',
            field=models.CharField(max_length=200, verbose_name='عنوان کتاب'),
        ),
    ]
