# Generated by Django 5.0.6 on 2024-06-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0015_book_music_book_alter_book_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mersanatrip',
            name='date',
        ),
        migrations.AlterField(
            model_name='mersanatrip',
            name='city',
            field=models.CharField(max_length=200, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='mersanatrip',
            name='image',
            field=models.FileField(upload_to='uploads/mersana_trip', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mersanatrip',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='mersanatrip',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='mersanatrip',
            name='trip_date',
            field=models.DateField(verbose_name='زمان سفر'),
        ),
        migrations.AlterField(
            model_name='mersanatrip',
            name='trip_description',
            field=models.TextField(verbose_name='شرح سفر'),
        ),
        migrations.AlterField(
            model_name='mersanatrip',
            name='trip_title',
            field=models.CharField(max_length=200, verbose_name='هنوان سفر'),
        ),
    ]
