# Generated by Django 5.0.6 on 2024-06-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0016_remove_mersanatrip_date_alter_mersanatrip_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mersanatrip',
            name='trip_date',
            field=models.DateTimeField(verbose_name='زمان سفر'),
        ),
        migrations.AlterField(
            model_name='mersanatrip',
            name='trip_title',
            field=models.CharField(max_length=200, verbose_name='عنوان سفر'),
        ),
    ]
