# Generated by Django 5.0.6 on 2024-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0017_alter_mersanatrip_trip_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mersanatrip',
            name='trip_date',
            field=models.DateField(verbose_name='زمان سفر'),
        ),
    ]
