# Generated by Django 5.0.6 on 2024-06-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0018_alter_mersanatrip_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mersanatrip',
            name='trip_date',
            field=models.CharField(max_length=100, verbose_name='زمان سفر'),
        ),
    ]
