# Generated by Django 5.0.6 on 2024-06-05 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0019_alter_mersanatrip_trip_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mersanapiano',
            name='image',
        ),
        migrations.AddField(
            model_name='mersanapiano',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/mersana_piano', verbose_name='ویدیو'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mersanapiano',
            name='date',
            field=models.DateField(verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='mersanapiano',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='mersanapiano',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='mersanapiano',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='mersanapiano',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
