# Generated by Django 5.0.6 on 2024-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0020_remove_mersanapiano_image_mersanapiano_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mersanapaints',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='mersanapaints',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='mersanapaints',
            name='image',
            field=models.ImageField(upload_to='uploads/mersana_paints', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mersanapaints',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='mersanapaints',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='mersanapaints',
            name='title',
            field=models.CharField(max_length=500, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='mersanapiano',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
    ]
