# Generated by Django 5.0.6 on 2024-06-05 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0022_alter_mersanaschool_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mersanafriends',
            name='date',
        ),
        migrations.AddField(
            model_name='mersanafriends',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mersanafriends',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='mersanafriends',
            name='image',
            field=models.ImageField(upload_to='uploads/mersana_friends', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mersanafriends',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='mersanafriends',
            name='name',
            field=models.CharField(max_length=20, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='mersanafriends',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='عنوان در url'),
        ),
    ]
