# Generated by Django 5.0.6 on 2024-06-07 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0023_remove_mersanafriends_date_mersanafriends_create_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mersanapic',
            name='date',
        ),
        migrations.AddField(
            model_name='mersanapic',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mersanamusic',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='mersanamusic',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='mersanamusic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='mersanamusic',
            name='music',
            field=models.FileField(upload_to='uploads/mersana_music', verbose_name='موسیقی'),
        ),
        migrations.AlterField(
            model_name='mersanamusic',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='mersanamusic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='mersanasports',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='mersanasports',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='mersanasports',
            name='image',
            field=models.FileField(upload_to='uploads/mersana_sports', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mersanasports',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='mersanasports',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='mersanasports',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
    ]
