# Generated by Django 5.0.6 on 2024-06-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0024_remove_mersanapic_date_mersanapic_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastnewsgallery',
            name='lastnews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_gallery', to='mersana_app.lastnews', verbose_name='آخرین خبر'),
        ),
    ]
