# Generated by Django 5.0.6 on 2024-06-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0025_alter_lastnewsgallery_lastnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastnews',
            name='image',
        ),
    ]
