# Generated by Django 5.0.6 on 2024-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0027_book_important_title_lastnews_important_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_friends', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title Of Friends')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='important_title',
        ),
        migrations.RemoveField(
            model_name='lastnews',
            name='important_title',
        ),
        migrations.RemoveField(
            model_name='mersanacreativity',
            name='important_title',
        ),
        migrations.RemoveField(
            model_name='mersanamusic',
            name='important_title',
        ),
        migrations.RemoveField(
            model_name='mersanapaints',
            name='important_title',
        ),
        migrations.RemoveField(
            model_name='mersanapiano',
            name='important_title',
        ),
        migrations.RemoveField(
            model_name='mersanaschool',
            name='important_title',
        ),
        migrations.RemoveField(
            model_name='mersanasports',
            name='important_title',
        ),
        migrations.RemoveField(
            model_name='mersanatrip',
            name='important_title',
        ),
    ]
