# Generated by Django 5.0.6 on 2024-06-10 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0028_importanttitle_remove_book_important_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importanttitle',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importanttitle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
    ]
