# Generated by Django 5.0.6 on 2024-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0029_importanttitle_created_at_importanttitle_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='importanttitle',
            name='title_of_book',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title Of book'),
        ),
        migrations.AddField(
            model_name='importanttitle',
            name='title_of_music',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title Of music'),
        ),
        migrations.AddField(
            model_name='importanttitle',
            name='title_of_news',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title Of news'),
        ),
        migrations.AddField(
            model_name='importanttitle',
            name='title_of_paint',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title Of paint'),
        ),
        migrations.AddField(
            model_name='importanttitle',
            name='title_of_piano',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title Of piano'),
        ),
        migrations.AddField(
            model_name='importanttitle',
            name='title_of_school',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title Of school'),
        ),
        migrations.AddField(
            model_name='importanttitle',
            name='title_of_sport',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title Of sport'),
        ),
        migrations.AddField(
            model_name='importanttitle',
            name='title_of_trip',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title Of trip'),
        ),
    ]
