# Generated by Django 5.0.6 on 2024-06-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0030_importanttitle_title_of_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='عنوان')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
        ),
        migrations.CreateModel(
            name='SectionTitlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name=' پیام')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('section_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mersana_app.sectiontitle', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='ImportantTitle',
        ),
    ]
