# Generated by Django 5.0.6 on 2024-06-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0031_sectiontitle_sectiontitlepage_delete_importanttitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectiontitlepage',
            old_name='title',
            new_name='title_page',
        ),
    ]
