# Generated by Django 5.0.6 on 2024-06-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0032_rename_title_sectiontitlepage_title_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontitlepage',
            name='section_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_title_page', to='mersana_app.sectiontitle', verbose_name=''),
        ),
    ]
