# Generated by Django 5.0.6 on 2024-06-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0034_aboutus_contactinfo_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(max_length=360, verbose_name='پیام'),
        ),
    ]
