# Generated by Django 5.0.6 on 2024-06-10 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0035_alter_contactus_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name=''),
            preserve_default=False,
        ),
    ]
