# Generated by Django 5.0.6 on 2024-06-12 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0037_visitcount_alter_contactinfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pic',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='نویسنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='page_counts',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='تعداد صفحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='ناشر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='مترجم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year_of_publication',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='سال انتشار'),
            preserve_default=False,
        ),
    ]
