# Generated by Django 5.0.6 on 2024-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0038_remove_book_date_remove_book_pic_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='مترجم'),
        ),
    ]
