# Generated by Django 5.0.6 on 2024-06-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0041_alter_mersanasports_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image_1',
            new_name='image',
        ),
    ]
