# Generated by Django 5.0.6 on 2024-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0042_rename_image_1_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mersanasports',
            name='image',
            field=models.ImageField(upload_to='mersana_sports', verbose_name='تصویر'),
        ),
    ]
