# Generated by Django 5.0.6 on 2024-06-13 19:29

import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0044_alter_mersanasports_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mersanasports',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mersanasports',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[3300, 2550], upload_to='uploads/mersana_sports'),
        ),
    ]
