# Generated by Django 5.0.6 on 2024-06-13 19:32

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mersana_app', '0045_mersanasports_created_at_alter_mersanasports_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[3300, 2550], upload_to='uploads/aboutUs', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[3300, 2550], upload_to='uploads/books', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='lastnewsgallery',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[3300, 2550], upload_to='uploads/lastnewsGallery', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mersanacreativity',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[3300, 2550], upload_to='uploads/mersana_creativity', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mersanafriends',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[3300, 2550], upload_to='uploads/mersana_friends', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mersanapaints',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[3300, 2550], upload_to='uploads/mersana_paints', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mersanapic',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[3300, 2550], upload_to='uploads/mersana_pictures', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mersanaschool',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[3300, 2550], upload_to='uploads/mersana_school', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='mersanatrip',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[3300, 2550], upload_to='uploads/mersana_trip', verbose_name='تصویر'),
        ),
    ]
