# Generated by Django 5.0.6 on 2024-05-23 17:41

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('mobile', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz123', editable=False, length=7, max_length=25, prefix='', primary_key=True, serialize=False, unique=True, verbose_name='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/profile_image', verbose_name='')),
                ('mobile', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('postal_code', models.CharField(max_length=10, verbose_name='')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
